# Generated by Django 5.1.1 on 2025-04-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_category_genre_genretitle_title_genretitle_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.CharField(max_length=50, unique=True, verbose_name='URL slug'),
        ),
    ]
