# Generated by Django 5.1.1 on 2025-04-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_genre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=50, unique=True, verbose_name='URL slug'),
        ),
    ]
