# Generated by Django 5.1.1 on 2025-05-06 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_alter_category_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name', 'slug'), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name', 'slug'), 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
    ]
