# Generated by Django 5.1.1 on 2025-05-07 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_alter_category_options_alter_genre_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['-year'], 'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
    ]
